### PR TITLE
Fix "incorrect password" message + log filter + autologin support

### PR DESCRIPTION
**Pull request by BratishkaErik**

### CODE REVIEW

**Comment by ElCholoGamer** [comment]
Using regex with user input is probably a bad idea, the expression might get messed up by the input. Instead, you might want to use manual string comparisons/checks instead of regex for the logs filter.

**Comment by BratishkaErik** [comment]
> Using regex with user input is probably a bad idea, the expression might get messed up by the input. Instead, you might want to use manual string comparisons/checks instead of regex for the logs filter.

I will try

**Comment by ElCholoGamer** [comment]
Oh yea, also 8e9eb206026a706e35cc8fb80058be20329faea8 actually inverts the purpose of `ULPlayer.onLoginAttempt`. I just realized the variable name should be `notExceeded` like you renamed it as, but the `if` condition should be `!notExceeded`.

**Comment by BratishkaErik** [comment]
> Using regex with user input is probably a bad idea, the expression might get messed up by the input. Instead, you might want to use manual string comparisons/checks instead of regex for the logs filter.

yes, it's hide /lobby etc. commands

**Comment by ElCholoGamer** [comment]
> 
> 
> > Oh yea, also [8e9eb20](https://github.com/ElCholoGamer/userlogin/commit/8e9eb206026a706e35cc8fb80058be20329faea8) actually inverts the purpose of `ULPlayer.onLoginAttempt`. I just realized the variable name should be `notExceeded` like you renamed it as, but the `if` condition should be `!notExceeded`.
> 
> In this case the message will not be send

The point is that the message will only be sent if the login attempts haven't been exceeded, since the plugin kicks the player otherwise.

**Comment by BratishkaErik** [comment]
> > > Oh yea, also [8e9eb20](https://github.com/ElCholoGamer/userlogin/commit/8e9eb206026a706e35cc8fb80058be20329faea8) actually inverts the purpose of `ULPlayer.onLoginAttempt`. I just realized the variable name should be `notExceeded` like you renamed it as, but the `if` condition should be `!notExceeded`.
> > 
> > 
> > In this case the message will not be send
> 
> The point is that the message will only be sent if the login attempts haven't been exceeded, since the plugin kicks the player otherwise.

yes, NOW plugin does exactly what you say. Before plugin never send this message

**Comment by BratishkaErik** [comment]
On proxy side (both Velocity and Bungeecord)  https://github.com/MineCastTeam/UserLoginBungee

**Comment by BratishkaErik** [comment]
Pull request is ready to review

**Comment by ElCholoGamer** [comment]
Alright, I'm on it 👍

**Review by ElCholoGamer — APPROVED** [review]

**Comment by ElCholoGamer** [comment]
PR merged. Thanks!

**Pull request merged**
